# Generated by Django 3.1.3 on 2020-11-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_auto_20201116_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.CharField(help_text='The MIMEType of the file', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='picture',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
